name: 'export-size-action'
description: 'GitHub Actions for export-size'
author: 'Anthony Fu <anthonyfu117@hotmail.com>'
branding:
  icon: 'box'
  color: 'black'
inputs:
  github_token:
    required: true
    description: 'a github access token'
  comment_token:
    required: false
    description: 'a github access token for commenting'
  build_script:
    required: false
    description: 'a custom npm script to build the files to check'
  paths:
    required: false
    description: 'paths for check export-size, useful for monorepo. split by comma, default to `.`'
  bundler:
    required: false
    description: 'define the bundler to be used by export-size, can be `esbuild` or `rollup`, default to `rollup`'
  node-version:
    description: Node version
    required: false
    default: '18'
runs:
  # @see https://github.com/orgs/community/discussions/53217#discussioncomment-6227341
  using: composite
  steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version || '18' }}
    - name: Action
      id: action
      run: node ${{ github.action_path }}/dist/index.js
      shell: ${{ (runner.os == 'Windows' && 'pwsh') || 'bash' }}
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_COMMENT_TOKEN: ${{ inputs.comment_token }}
        INPUT_BUILD_SCRIPT: ${{ inputs.build_script }}
        INPUT_PATHS: ${{ inputs.paths }}
        INPUT_BUNDLER: ${{ inputs.bundler }}
